INSERT INTO canton ('name', 'value', 'level') VALUES
    ('Aargau', 1, 0),
    ('Appenzell Ausserrhoden', 1, 0),
    ('Appenzell Innerrhoden', 1, 0),
    ('Basel-Landschaft', 1, 0),
    ('Basel-Stadt', 1, 0),
    ('Bern', 1, 0),
    ('Fribourg', 1, 0),
    ('Geneva', 1, 0),
    ('Glarus', 1, 0),
    ('Grisons', 1, 0),
    ('Jura', 1, 0),
    ('Lucerne', 1, 0),
    ('Neuchâtel', 1, 0),
    ('Nidwalden', 1, 0),
    ('Obwalden', 1, 0),
    ('Schaffhausen', 1, 0),
    ('Schwyz', 1, 0),
    ('Solothurn', 1, 0),
    ('St. Gallen', 1, 0),
    ('Thurgau', 1, 0),
    ('Ticino', 1, 0),
    ('Uri', 1, 0),
    ('Valais', 1, 0),
    ('Vaud', 1, 0),
    ('Zug', 1, 0),
    ('Zurich', 1, 0);

INSERT INTO user ('username', 'firstname', 'lastname', 'team_id') VALUES
   ('icf', 'Isaac', 'Feldman', '0'),
   ('aaronlieb', 'Aaron', 'Lieberman', '1');    
